#!/bin/bash
# upda = "updates all". It updates packages: apt, flatpak y snap).

# It's not very sofisticated, but it saves time.

echo -e "\e[32m\n\n"
echo -e "///////////// UPDATING /////////////"

echo -e "\n\e[32m"
echo -e "APT UPDATE"
    sudo apt update


echo -e "\n\e[32m"
echo -e "APT UPGRADE"
    sudo apt upgrade


echo -e "\n\e[32m"
echo -e "APT AUTOREMOVE"
    sudo apt autoremove


echo -e "\n\e[32m"
echo -e "FLATPAK UPDATE"
    sudo flatpak update


echo -e "\n\e[32m"
echo -e "SNAP REFRESH"
    sudo snap refresh


echo -e "\n\e[32m"
echo -e "///////////// UPDATED /////////////"
echo -e "\n\n\e[0m"
